apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: webrom
data:
  default.conf: |
    server {
      listen 443 ssl;
      server_name localhost;

      ssl_certificate /etc/ssl/cert.pem;
      ssl_certificate_key /etc/ssl/key.pem;

      location /cgi-bin/ {
        proxy_pass http://app.approm.svc.cluster.local:81;
      }

      location / {
        proxy_pass http://web:80;
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-certs
  namespace: webrom
type: Opaque
data:
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ6VENDQTdXZ0F3SUJBZ0lVSCtsZFRjNWV0cFNubXprc211UE9tT2psbCtJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RqRUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWNNQmtGdVpHVmllVEVVTUJJR0ExVUVDZ3dMVUdWdQpaMlZpYVc1blpXNHhIakFjQmdOVkJBTU1GV3h2WTJGc2FHOXpkQzVzYjJOaGJHUnZiV0ZwYmpFZ01CNEdDU3FHClNJYjNEUUVKQVJZUmMydHlkV1ZBY0dWdVoyVmlhVzVuWlc0d0hoY05Nall3TkRFMk1UQXhNakU0V2hjTk1qY3cKTkRFMk1UQXhNakU0V2pCMk1Rc3dDUVlEVlFRR0V3SlZVekVQTUEwR0ExVUVCd3dHUVc1a1pXSjVNUlF3RWdZRApWUVFLREF0UVpXNW5aV0pwYm1kbGJqRWVNQndHQTFVRUF3d1ZiRzlqWVd4b2IzTjBMbXh2WTJGc1pHOXRZV2x1Ck1TQXdIZ1lKS29aSWh2Y05BUWtCRmhGemEzSjFaVUJ3Wlc1blpXSnBibWRsYmpDQ0FpSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQU1BL0hDaEJYUDFoZlFaaDNTc2xDY1JWZFJCU1lheDFWeWp4VTZ5bwptUTlqSFNwdDloenRwSnM0WUJGWThlMFBmZmZUcHFCSEh2UlcvVnBpVk9EeG1zdXAwdzBtdjZ4MmtaRFlIeFc2ClB0WTR2czZXZmdVZGdXV3NocW1sTXRiVGp5UlBIdXRaaVRGRXkzSGRpUFM1TkNMQmM3bVZ1dUlYa3hLck90OEQKR1hiUklURFRKb2MwelFtcXRwK0JSY0tPbG1vZk16am0yUkJwUkplaDMvWnVLWFFRTXFJREtXMmlIeCtIeXhSZQpHdm8wMlRTKzNWdmF6cDNwcSsySmdiOFRSRzBGdld4QVF1SDF4WGU4Lzk4WDFWbnJ3elBWK0l0dkRacVFXNFE2CnVGUHByY0drcDRNS2xad0JPYW1keHBHNENUUVpxN0VPaTUwZWZOQzEvYlptUXJjL1RCUEhZZmJyeWszaElRZU8KbXJ3YzRiMWJBdHViMHJwY3h1eUI0TVZxbXFRdWxuampBLzhMc0ZtVUJKSDBrSXF2RXZwR1BXakFJcElIenJIZAovak1ycUZjR3FZQVJkMENhcjdLNVpIVGtNdGtYQkgrcVpOamNCL2JqSGRLMHNDLzNCbmZiMHVFQUhWRVZjV0RQCjhPOGNGWUFodFU2QWd4TWUxTy8xbVBpVXRxcGNiYmtQUGJTaVJ0am52RFNGRmZOcUQrb1Y0Y0JtNjV5MTVnWTkKV0JBRk9IZWxTbVdBQTZvb2RqT2dVejl5SzRxK1JpZlhaOFA2c2VyVThWSDMrSkZUMm5WSTdlaUxpT0F0SnI4cQp0djlLWFVISGl1M2ZXcGU0SlZnVUpaZ1JJOE9yc3dZK3NsK000OWkwbktpUkowNVdYWHVNQ3lLUk9vVWRjVjM5CmVGeEJBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlJ4M000aEFqYmQyalMwNzRJOFE3NllyZTZwdlRBZkJnTlYKSFNNRUdEQVdnQlJ4M000aEFqYmQyalMwNzRJOFE3NllyZTZwdlRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQzhBSXVSTDhuNmpPRTQxNWJkcytkMW90dk0zNkpmRjJ1c2lva1R2bUFwCk1MSHRMQTA5Sk50citpNktLZU0wUzFxeGRmT3hRWWpxN0VqTkxnRFFaUXVDbnFjK0lxd3VnbnJSeEZLejArM2sKUmJvQi9kTExEelJXLzBwVE8yUEZDMjdqamxIWWxFcXBxU2NwS2Yxa1VaZlpSMHc5VzlPL0JudWRNdzdSdy8vaApSanp0UDBJQitBb2kxaElZSzN5UWpKb1l1REFmS04rUkFwRmVkcVZ1bEtvTlBRZnRiLzA2cDV1RTh5NGljM0N4CmFaMmtkZUxkaVBUYkY5eFFHcDI0MzhGWEErcnFxdStBUFhncE9KZWI3RXBzOVJXZFBhdGRSSUU5cHYwbm8zWG4KVVlPb2hjYmpYSFNCVVFjRnRYbVYxVG1FVW44ckNMeHlRbXVVak9SWk4wQlU3YzJWU3ZsbXNaZnRZUUN0dXEvdQpqOWlnWWFvWXJCai9ycWVGUUppK2trVzQvYW9LZFlsc1FsK3JTcEE2RjJIcmhhaXRlZC9FVC9vcjA3TjRaZnJUCnVSZE9RKzF5VENWWUFwTGFVM0tFSUZMZW1DNG55bFdqbDlGZVJ5Yms1dFZXRDhLK2hpSnRMY053Y3JtZTVXejkKL1ZEVEdadmdqRVpXS0RtUjNNbUU1emlRUTJWcjdOSXVmUkJsT21kdncyQ3Q4QXJpaVN5TDFtRC90bzRQNG9YNQpiakxxRzZpTEdYVjZTNEpGclMvd1dvWlkyQjAwRDh5U3NDekZrM3R3MG5WK0FuWThlM0o3UHpFZVhlQm1nVmV4CkQySHpadGo2TTVYdUJzTzJmMDliQ3dEQmtIMW9JbnZHMm9vOXFPK3ZYR1hsZG1pR3l2alM1eFV2YWRqUnBwSSsKY3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  key.pem:  LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRREFQeHdvUVZ6OVlYMEcKWWQwckpRbkVWWFVRVW1Hc2RWY284Vk9zcUprUFl4MHFiZlljN2FTYk9HQVJXUEh0RDMzMzA2YWdSeDcwVnYxYQpZbFRnOFpyTHFkTU5KcitzZHBHUTJCOFZ1ajdXT0w3T2xuNEZIWUZscklhcHBUTFcwNDhrVHg3cldZa3hSTXR4CjNZajB1VFFpd1hPNWxicmlGNU1TcXpyZkF4bDIwU0V3MHlhSE5NMEpxcmFmZ1VYQ2pwWnFIek00NXRrUWFVU1gKb2QvMmJpbDBFREtpQXlsdG9oOGZoOHNVWGhyNk5OazB2dDFiMnM2ZDZhdnRpWUcvRTBSdEJiMXNRRUxoOWNWMwp2UC9mRjlWWjY4TXoxZmlMYncyYWtGdUVPcmhUNmEzQnBLZURDcFdjQVRtcG5jYVJ1QWswR2F1eERvdWRIbnpRCnRmMjJaa0szUDB3VHgySDI2OHBONFNFSGpwcThIT0c5V3dMYm05SzZYTWJzZ2VERmFwcWtMcFo0NHdQL0M3QloKbEFTUjlKQ0tyeEw2Umoxb3dDS1NCODZ4M2Y0eks2aFhCcW1BRVhkQW1xK3l1V1IwNURMWkZ3Ui9xbVRZM0FmMgo0eDNTdExBdjl3WjMyOUxoQUIxUkZYRmd6L0R2SEJXQUliVk9nSU1USHRUdjlaajRsTGFxWEcyNUR6MjBva2JZCjU3dzBoUlh6YWcvcUZlSEFadXVjdGVZR1BWZ1FCVGgzcFVwbGdBT3FLSFl6b0ZNL2NpdUt2a1luMTJmRCtySHEKMVBGUjkvaVJVOXAxU08zb2k0amdMU2EvS3JiL1NsMUJ4NHJ0MzFxWHVDVllGQ1dZRVNQRHE3TUdQckpmak9QWQp0Snlva1NkT1ZsMTdqQXNpa1RxRkhYRmQvWGhjUVFJREFRQUJBb0lDQUFNamhLUXJuUWNPQm1xS1FvQW4xS2I5CjlqRlVCd0EzMGpwNjVqRFZkOXBHZGYxeFdpbFN2L05BMG1DMklRMEx5YlM0SWVwUC92TmlVRFNma2w4eDBxTXMKbktPRVZIRE9ac1lFb1UxTGd5Y2dPZzFKYTdsTnFBVXU4ZXZuSkpOWlZPYjAyNzVmOGR0NkVoQkQyNjZUTDRTNQp2OWZ4MStGRkhVT2F4QlZNQ2FoazliUEVYc2FxV0FhbVlPRHR6V1BGekRMalc0UzhVQ0x5ZFFvOHZGbGJweFdjCkJoZWJFWndXbjRkMlFoeU5CTWU5QVNiWlR1Zm5CS1NUWWhrNHU0T1JIdmJndHgwRFY1UTAzUXA5YlhnSS9aVEEKUXFtZi9yVFlGVkxHdEpmT0ZhQlpHbHNsQXc4aXB4cXE4blFRZldOM3E3N01CSCtaaXpIL2cyNHM2bjJGNGVUdwp2YzQ2SXRWN21YeURXUEVlL1Nld0JWRVJHZHFMWkdvV2lkOFlacUFOZ09hN1pQMEZEVW1yVU84L25YL0xpQktlCmpSS0ZZSzBkQUxZSWxhZWV6WHJlN09GVjJFS1hQa3krWGRWQkt6ejlqTm5vUmtjblB1STZpbU5aOU9sNFBmVkYKcW9BTldEZ25Ob25OY1VQM0xTQ2VsZW1ZNUNIUGJNZElncXJjeFYzZ2M1N1ZDb3RHVmFiOGZBZ1pOT3dsN2ZTYgpvSmF6NlJPUlRVdmRBb00rZGVESHFWTWNxVXQ0UGxsUUdCbzI0eHd0Z1YrQWhvMDd6QmFTOVRnRlM5WDV1NVBGCm5QSmNQTXpQaVZMWVZheGV4dnlBbjlZcDJlZWNWVUVmSVdxZkpHRDF5TTl2Wlg3MUdlaGFaN1YvTFVSU3AvMjEKOXd1MjJqVFBDME51YnpHRStkY1pBb0lCQVFEMVB1S1lyWTlyOG5NdlIyaU5uNVdUNjhpb2RYL294QTNuOSs4dgo3Z1ZMdS8rckU1aWlXL3k2dmZSeUVxc00rNHJxRVVhdEpQeGdvcmpWK2pSMjhXVVBaa29mcVJZQ0xlYXRIZ25NCnpsWjdENGw3MTBlekNCRVR4UE4zVUFXOFNkVXJRYUNyUHl4dWxDcE1IcDdVWjk5N2ZmamNDQTJGWkJ4cHliWkcKcTNXMmN6MzI1M2pPdUhyVmRCaDh4ZVV2ajFRR2ZRME15VlQyZXUzZmN0UmZyNFZIWVVOWElONWVEaWRnRDlHOApuRXh1UlNvaVJIV3gyWDJlL2JHQmNyNW44bittSmRYcTMyUUJyd05HYXNIRFBMQ0c0R3FSSkNHMml4THJyZTFWCnRzT05meXFqVnRMdC81TDVKMjZPYVhwZVlkOWpmNExnajljeTZzR01oNDlkTjU1ekFvSUJBUURJclVKc0xZNmkKRUVwM0g5bGw0U1pBOGQ0Ym1seldQTHdFMlNBdmtCSHFBWVJpRlRNR05JUlRNZWF0QXNwdEhkQzZFeVpVM0g0bgpqbThpbDZ1MVF2UkxOZ2FDSWtpdTVONVFlMExEVVMwT1Fvc21ZSTQyQ2FWM3ViVlhwTWxZUE5kTUVBaURTeGZCCk9JVU9jM0FOZFFOQlBnRVpQWmdzdnAxbG43WTZtS2t4S2p2b3lMQURETTRhazNNVkVNZ3hJbnlPMU5GdWwxa3EKWHkyUmRKSFAvZVhFZzhKc3NHOVJYOWhVUTJDeUhKMnh0Rjh5dVFWU3NvMW50MWJleGd3L3ZlN3hBTFlOWSt0VwpJL0NhRExCQjFIQmFJckY4UHpYYUlQNjVyUkdidmNKS3dYNnFXYmtuVnc2Sk1hdjRqeXhOZmd4aklubHBkNHdsCldpMWpUazNlSWhsN0FvSUJBUURXLzVCTFpTeXM1OW9QQXIwb0cxVllYb2FGR0sxUDlFQjBzaWtnamJ4YXpxK3UKM1BrY3JTUDgybmFvWXJGT0tsOTRJRGtqcFo4VFlOUkYwcG1ZQkx3aUtmeWxrT2hZZE1FYjE0K2oydWg1N2Y4TApjSW5NN0M5OGMxYzFyQk83SThjYnF1Y2QrYjRNR3h5UnF1NTNLN0VDWkVkOUxob2NiTTF6K0lBeHFETUVCamUyCmN1cTMzNGJnQm0xSlJYeE1tNHlBTzdUckZyM0RiN1dHQlBjbUE0d0dMY0NKYTZsR0w0Wlpjc1RlWXUrbVpFQXgKMW02UHdpbWM3cTlrMnFFT0k4dkFicjhBcjJMUER3MEIrS2x4YlkwY1VUVmJsSjl4bHE2NXFycThRQU5qMHE0ZwprQWRPMnBXUWsvOGFIbUpHeCtxOUlaWXRKQ3oyMkZOaHpaM2pqTlQ5QW9JQkFHMWpaRzJyZDdDSHlNK2VvTmFVCklGSU9oYy91R09UL1BrNDJQUUV3TzFPZmVCWXZFQjAxeTF1K084dmJWWlNkU0FYbUltTG52aXk1eTRMRHdtbVEKRWJKZHhMWnpFY09rSmpzZ3RZZmFYQUVGN093Q2ZnS2V4MyszejAzekdYM3J6RUErRFNYa2JSSjZTSzFUNTZTdQpRQlAwUkkwSnNrWFJzZUtQYUxvUU5Vb0RoNXlncUxGQTdhZzI3K2h2dVhCdktBNkRtNVg1RWpXeXBCaEJ2cW50CjhLMXFWVFVDQit3SG50aHYwZW5GQjRDeW5hSDhrUlkvRmkyUEZ0OWdmWlRSWjhvZlpSMXZkZjBDb2tpVzJnMUkKUytZV08wRkxBNFBmc0hwdUNNY29iUnhxMVN6dXM2cnFIWlpUYVRhWWRNSFpEOCtLSHp5S1dlNlNkV05JYjlIQwpMTGtDZ2dFQVVIYTVwYzNZcEo1dUtYbmNNemI1MW5SWHJ3YnFjQjQ3RkVqZk44WkZ0di83TDR4UU9hMlZsZFZwCndHTmlGZFhQWFhsMEdkRm12MHpwQnZ0K1JEeWYxVjNCeURWMGxVTUtPMDI4V0c1TDkxSzBjMzZNbjBFL2U2VncKS1hDUXFFdmVGMkxkZkc1cmV0TWRkRUg3R21zUXFKNklkYjJia3BrN0tlbjdvUzhkTHpvNjI5VExoVFlWUHVCSwp2a3N3WDA3VDJxK3RwUnlyY1FveWpROTJ5cUVMc0psdWNrUXlMYXJma0N6MmdtNFd6VXhiNnUxT3BjTlpvbWh1Ci9rRzdZUE8wOTNhb3c5bVFkZWJxM0p6MWNWSEhZVThNSEZLN3kwYkhJV1FORVNuVmRFYXYzRUtVbzhocTZUYTkKeWRSNXZFVjR3SitOc0gvbjFzRFh2bE1RbWxva0VnPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https
  namespace: webrom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-https
  template:
    metadata:
      labels:
        app: nginx-https
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 443

        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: nginx-certs
          mountPath: /etc/ssl

        readinessProbe:
          tcpSocket:
            port: 443
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          tcpSocket:
            port: 443
          initialDelaySeconds: 10
          periodSeconds: 10

      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: nginx-certs
        secret:
          secretName: nginx-certs

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-https
  namespace: webrom
spec:
  selector:
    app: nginx-https
  ports:
    - port: 443
      targetPort: 443
  type: ClusterIP
