# start: nye PVC-er for persistens (person 4)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bidrag-pvc
  labels:
    app: allpodd
    component: bidrag-db
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pseudonym-pvc
  labels:
    app: allpodd
    component: pseudonym-db
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# slutt: nye PVC-er for persistens (person 4)