# start: PersistentVolumeClaim-er for varig lagring av databasedata - oppfyller F3 (persistens over nedetid og omstart) og NF2 (orkestrering med Kubernetes) (person 4)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bidrag-pvc
  labels:
    # start: Identifikasjonsetiketter for backend-lagringsressurs - oppfyller NF6 (merking av skyverdier) (person 4)
    app: allpodd
    component: bidrag-db
    tier: backend
    data-classification: restricted-user-content
    security: hardened
    # slutt: Identifikasjonsetiketter for backend-lagringsressurs - oppfyller NF6 (merking av skyverdier) (person 4)
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pseudonym-pvc
  labels:
    # start: Identifikasjonsetiketter for backend-lagringsressurs - oppfyller NF6 (merking av skyverdier) (person 4)
    app: allpodd
    component: pseudonym-db
    tier: backend
    data-classification: personal-data
    security: hardened
    # slutt: Identifikasjonsetiketter for backend-lagringsressurs - oppfyller NF6 (merking av skyverdier) (person 4)
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# slutt: PersistentVolumeClaim-er for varig lagring av databasedata - oppfyller F3 (persistens over nedetid og omstart) og NF2 (orkestrering med Kubernetes) (person 4)
